spring:
  application:
    name: user
  cloud:
    config:
      discovery:
        service-id: CONFIG
        enabled: true
      profile: prod
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
